### ISSUE TITLE
[Epic] Add the NWSL 

### ISSUE THREAD

**Issue by dannypage** [Skrimmage/Data-Platform#8]
- [ ] Create a Dagster Resource Class to query the NWSL API 
- [ ] Create Dagster Asset to Extract data
- [ ] Create Dagster Asset to Load data into DuckDB
- [ ] Publish data into Evidence
